ApiConfig:
  port: 8080

TimeZone:
  Zone: 'CTS'
  Time: 28800

DatabaseConfig:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password: 123456
  Name: gin
  Charset: utf8mb4

MysqlConf:
  List:
    'default':
      DriverName: 'mysql'
      DataSourceName: 'root:123456@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing'
      MaxOpenConn: 50
      MaxIdleConn: 20
      MaxConnLifeTime: 100
      Prefix: 'cmf_'
    'read':
      DriverName: 'mysql'
      DataSourceName: 'root:123456@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing'
      MaxOpenConn: 50
      MaxIdleConn: 20
      MaxConnLifeTime: 100
      Prefix: 'cmf_'
  Split: 3

RedisConfig:
  Host: 127.0.0.1,
  Port: 6379
  Password: 123
  Db: 2
