HttpConf:
  Addr: ':20152'
  UploadAuth: 'A958EFDDB469B74FF3DEB81717914225'
  ApiAesKey: 'C77A9FF7F323B5404902102257503C2F'

TimeZone:
  Zone: 'CTS'
  Time: 28800

MysqlConf:
  List:
    'default':
      DriverName: 'mysql'
      DataSourceName: 'root:123456@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing'
      MaxOpenConn: 50
      MaxIdleConn: 20
      MaxConnLifeTime: 100
      Prefix: 'cmf_'
    'read':
      DriverName: 'mysql'
      DataSourceName: 'root:123456@tcp(127.0.0.1:3306)/gin?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing'
      MaxOpenConn: 50
      MaxIdleConn: 20
      MaxConnLifeTime: 100
      Prefix: 'cmf_'
  Split: 3

RedisConfig:
  Host: 127.0.0.1,
  Port: 6379
  Password: 123
  Db: 2
